package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Category  {

    private java.lang.Integer categoryID;  // t
    private java.lang.String categoryName;  // t
    private java.lang.String description;  // t
    private byte[] picture;  // t

    public java.lang.Integer getCategoryID() {
        return this.categoryID;
    }

    public void setCategoryID(java.lang.Integer categoryID) {
        this.categoryID = categoryID;
    }

    public java.lang.String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(java.lang.String categoryName) {
        this.categoryName = categoryName;
    }

    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    public byte[] getPicture() {
        return this.picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
}