package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Customer  {

    private java.lang.String customerID;  // t
    private java.lang.String companyName;  // t
    private java.lang.String contactName;  // t
    private java.lang.String contactTitle;  // t
    private java.lang.String address;  // t
    private java.lang.String city;  // t
    private java.lang.String region;  // t
    private java.lang.String postalCode;  // t
    private java.lang.String country;  // t
    private java.lang.String phone;  // t
    private java.lang.String fax;  // t

    public java.lang.String getCustomerID() {
        return this.customerID;
    }

    public void setCustomerID(java.lang.String customerID) {
        this.customerID = customerID;
    }

    public java.lang.String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(java.lang.String companyName) {
        this.companyName = companyName;
    }

    public java.lang.String getContactName() {
        return this.contactName;
    }

    public void setContactName(java.lang.String contactName) {
        this.contactName = contactName;
    }

    public java.lang.String getContactTitle() {
        return this.contactTitle;
    }

    public void setContactTitle(java.lang.String contactTitle) {
        this.contactTitle = contactTitle;
    }

    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }

    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getRegion() {
        return this.region;
    }

    public void setRegion(java.lang.String region) {
        this.region = region;
    }

    public java.lang.String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(java.lang.String postalCode) {
        this.postalCode = postalCode;
    }

    public java.lang.String getCountry() {
        return this.country;
    }

    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    public java.lang.String getPhone() {
        return this.phone;
    }

    public void setPhone(java.lang.String phone) {
        this.phone = phone;
    }

    public java.lang.String getFax() {
        return this.fax;
    }

    public void setFax(java.lang.String fax) {
        this.fax = fax;
    }
}