package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class EmployeesTerritory  {

    private Integer employeeID;  // t(EmployeeID)
    private Integer territoryID;  // t(TerritoryID)

    public Integer getEmployeeID() {
        return this.employeeID;
    }

    public void setEmployeeID(Integer employeeID) {
        this.employeeID = employeeID;
    }

    public Integer getTerritoryID() {
        return this.territoryID;
    }

    public void setTerritoryID(Integer territoryID) {
        this.territoryID = territoryID;
    }
}