package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Employee  {

    private java.lang.Integer employeeID;  // t
    private java.lang.String lastName;  // t
    private java.lang.String firstName;  // t
    private java.lang.String title;  // t
    private java.lang.String titleOfCourtesy;  // t
    private java.lang.String birthDate;  // t
    private java.lang.String hireDate;  // t
    private java.lang.String address;  // t
    private java.lang.String city;  // t
    private java.lang.String region;  // t
    private java.lang.String postalCode;  // t
    private java.lang.String country;  // t
    private java.lang.String homePhone;  // t
    private java.lang.String extension;  // t
    private java.lang.String photo;  // t
    private java.lang.String notes;  // t
    private java.lang.String photoPath;  // t

    public java.lang.Integer getEmployeeID() {
        return this.employeeID;
    }

    public void setEmployeeID(java.lang.Integer employeeID) {
        this.employeeID = employeeID;
    }

    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }

    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }

    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }

    public java.lang.String getTitleOfCourtesy() {
        return this.titleOfCourtesy;
    }

    public void setTitleOfCourtesy(java.lang.String titleOfCourtesy) {
        this.titleOfCourtesy = titleOfCourtesy;
    }

    public java.lang.String getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(java.lang.String birthDate) {
        this.birthDate = birthDate;
    }

    public java.lang.String getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(java.lang.String hireDate) {
        this.hireDate = hireDate;
    }

    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }

    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getRegion() {
        return this.region;
    }

    public void setRegion(java.lang.String region) {
        this.region = region;
    }

    public java.lang.String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(java.lang.String postalCode) {
        this.postalCode = postalCode;
    }

    public java.lang.String getCountry() {
        return this.country;
    }

    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    public java.lang.String getHomePhone() {
        return this.homePhone;
    }

    public void setHomePhone(java.lang.String homePhone) {
        this.homePhone = homePhone;
    }

    public java.lang.String getExtension() {
        return this.extension;
    }

    public void setExtension(java.lang.String extension) {
        this.extension = extension;
    }

    public java.lang.String getPhoto() {
        return this.photo;
    }

    public void setPhoto(java.lang.String photo) {
        this.photo = photo;
    }

    public java.lang.String getNotes() {
        return this.notes;
    }

    public void setNotes(java.lang.String notes) {
        this.notes = notes;
    }

    public java.lang.String getPhotoPath() {
        return this.photoPath;
    }

    public void setPhotoPath(java.lang.String photoPath) {
        this.photoPath = photoPath;
    }
}