package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class EmployeesTerritory  {

    private java.lang.Integer employeeID;  // t
    private java.lang.Integer territoryID;  // t

    public java.lang.Integer getEmployeeID() {
        return this.employeeID;
    }

    public void setEmployeeID(java.lang.Integer employeeID) {
        this.employeeID = employeeID;
    }

    public java.lang.Integer getTerritoryID() {
        return this.territoryID;
    }

    public void setTerritoryID(java.lang.Integer territoryID) {
        this.territoryID = territoryID;
    }
}