package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class InternationalOrder  {

    private java.lang.Integer orderID;  // t
    private java.lang.String customsDescription;  // t
    private java.lang.String exciseTax;  // t

    public java.lang.Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(java.lang.Integer orderID) {
        this.orderID = orderID;
    }

    public java.lang.String getCustomsDescription() {
        return this.customsDescription;
    }

    public void setCustomsDescription(java.lang.String customsDescription) {
        this.customsDescription = customsDescription;
    }

    public java.lang.String getExciseTax() {
        return this.exciseTax;
    }

    public void setExciseTax(java.lang.String exciseTax) {
        this.exciseTax = exciseTax;
    }
}