package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class InternationalOrder  {

    private Integer orderID;  // t
    private String customsDescription;  // t
    private String exciseTax;  // t

    public Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }

    public String getCustomsDescription() {
        return this.customsDescription;
    }

    public void setCustomsDescription(String customsDescription) {
        this.customsDescription = customsDescription;
    }

    public String getExciseTax() {
        return this.exciseTax;
    }

    public void setExciseTax(String exciseTax) {
        this.exciseTax = exciseTax;
    }
}