package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class Invoice  {

    private Object shipName;  // q
    private Object shipAddress;  // q
    private Object shipCity;  // q
    private Object shipRegion;  // q
    private Object shipPostalCode;  // q
    private Object shipCountry;  // q
    private Object customerID1;  // q
    private Object companyName;  // q
    private Object address1;  // q
    private Object city1;  // q
    private Object region1;  // q
    private Object postalCode1;  // q
    private Object country1;  // q
    private Object salesperson;  // q
    private Object orderID;  // q
    private Object orderDate;  // q
    private Object requiredDate;  // q
    private Object shippedDate;  // q
    private Object productID;  // q
    private Object productName;  // q
    private Object unitPrice;  // q
    private Object quantity;  // q
    private Object discount;  // q
    private Object extendedPrice;  // q
    private Object freight;  // q

    public Object getShipName() {
        return this.shipName;
    }

    public void setShipName(Object shipName) {
        this.shipName = shipName;
    }

    public Object getShipAddress() {
        return this.shipAddress;
    }

    public void setShipAddress(Object shipAddress) {
        this.shipAddress = shipAddress;
    }

    public Object getShipCity() {
        return this.shipCity;
    }

    public void setShipCity(Object shipCity) {
        this.shipCity = shipCity;
    }

    public Object getShipRegion() {
        return this.shipRegion;
    }

    public void setShipRegion(Object shipRegion) {
        this.shipRegion = shipRegion;
    }

    public Object getShipPostalCode() {
        return this.shipPostalCode;
    }

    public void setShipPostalCode(Object shipPostalCode) {
        this.shipPostalCode = shipPostalCode;
    }

    public Object getShipCountry() {
        return this.shipCountry;
    }

    public void setShipCountry(Object shipCountry) {
        this.shipCountry = shipCountry;
    }

    public Object getCustomerID1() {
        return this.customerID1;
    }

    public void setCustomerID1(Object customerID1) {
        this.customerID1 = customerID1;
    }

    public Object getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(Object companyName) {
        this.companyName = companyName;
    }

    public Object getAddress1() {
        return this.address1;
    }

    public void setAddress1(Object address1) {
        this.address1 = address1;
    }

    public Object getCity1() {
        return this.city1;
    }

    public void setCity1(Object city1) {
        this.city1 = city1;
    }

    public Object getRegion1() {
        return this.region1;
    }

    public void setRegion1(Object region1) {
        this.region1 = region1;
    }

    public Object getPostalCode1() {
        return this.postalCode1;
    }

    public void setPostalCode1(Object postalCode1) {
        this.postalCode1 = postalCode1;
    }

    public Object getCountry1() {
        return this.country1;
    }

    public void setCountry1(Object country1) {
        this.country1 = country1;
    }

    public Object getSalesperson() {
        return this.salesperson;
    }

    public void setSalesperson(Object salesperson) {
        this.salesperson = salesperson;
    }

    public Object getOrderID() {
        return this.orderID;
    }

    public void setOrderID(Object orderID) {
        this.orderID = orderID;
    }

    public Object getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Object orderDate) {
        this.orderDate = orderDate;
    }

    public Object getRequiredDate() {
        return this.requiredDate;
    }

    public void setRequiredDate(Object requiredDate) {
        this.requiredDate = requiredDate;
    }

    public Object getShippedDate() {
        return this.shippedDate;
    }

    public void setShippedDate(Object shippedDate) {
        this.shippedDate = shippedDate;
    }

    public Object getProductID() {
        return this.productID;
    }

    public void setProductID(Object productID) {
        this.productID = productID;
    }

    public Object getProductName() {
        return this.productName;
    }

    public void setProductName(Object productName) {
        this.productName = productName;
    }

    public Object getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Object unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Object getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Object quantity) {
        this.quantity = quantity;
    }

    public Object getDiscount() {
        return this.discount;
    }

    public void setDiscount(Object discount) {
        this.discount = discount;
    }

    public Object getExtendedPrice() {
        return this.extendedPrice;
    }

    public void setExtendedPrice(Object extendedPrice) {
        this.extendedPrice = extendedPrice;
    }

    public Object getFreight() {
        return this.freight;
    }

    public void setFreight(Object freight) {
        this.freight = freight;
    }
}