package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class OrderDetailsExtended  {

    private java.lang.Object orderID;  // q
    private java.lang.Object productID;  // q
    private java.lang.Object productName;  // q
    private java.lang.Object unitPrice;  // q
    private java.lang.Object quantity;  // q
    private java.lang.Object discount;  // q
    private java.lang.Object extendedPrice;  // q

    public java.lang.Object getOrderID() {
        return this.orderID;
    }

    public void setOrderID(java.lang.Object orderID) {
        this.orderID = orderID;
    }

    public java.lang.Object getProductID() {
        return this.productID;
    }

    public void setProductID(java.lang.Object productID) {
        this.productID = productID;
    }

    public java.lang.Object getProductName() {
        return this.productName;
    }

    public void setProductName(java.lang.Object productName) {
        this.productName = productName;
    }

    public java.lang.Object getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(java.lang.Object unitPrice) {
        this.unitPrice = unitPrice;
    }

    public java.lang.Object getQuantity() {
        return this.quantity;
    }

    public void setQuantity(java.lang.Object quantity) {
        this.quantity = quantity;
    }

    public java.lang.Object getDiscount() {
        return this.discount;
    }

    public void setDiscount(java.lang.Object discount) {
        this.discount = discount;
    }

    public java.lang.Object getExtendedPrice() {
        return this.extendedPrice;
    }

    public void setExtendedPrice(java.lang.Object extendedPrice) {
        this.extendedPrice = extendedPrice;
    }
}