package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class OrderDetail  {

    private java.lang.Integer orderID;  // t
    private java.lang.Integer productID;  // t
    private java.lang.String unitPrice;  // t
    private java.lang.Integer quantity;  // t
    private java.lang.Float discount;  // t

    public java.lang.Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(java.lang.Integer orderID) {
        this.orderID = orderID;
    }

    public java.lang.Integer getProductID() {
        return this.productID;
    }

    public void setProductID(java.lang.Integer productID) {
        this.productID = productID;
    }

    public java.lang.String getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(java.lang.String unitPrice) {
        this.unitPrice = unitPrice;
    }

    public java.lang.Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(java.lang.Integer quantity) {
        this.quantity = quantity;
    }

    public java.lang.Float getDiscount() {
        return this.discount;
    }

    public void setDiscount(java.lang.Float discount) {
        this.discount = discount;
    }
}