package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class OrderDetailsExtended  {

    private Object orderID;  // q(OrderID)
    private Object productID;  // q(ProductID)
    private Object productName;  // q(ProductName)
    private Object unitPrice;  // q(UnitPrice)
    private Object quantity;  // q(Quantity)
    private Object discount;  // q(Discount)
    private Object extendedPrice;  // q(ExtendedPrice)

    public Object getOrderID() {
        return this.orderID;
    }

    public void setOrderID(Object orderID) {
        this.orderID = orderID;
    }

    public Object getProductID() {
        return this.productID;
    }

    public void setProductID(Object productID) {
        this.productID = productID;
    }

    public Object getProductName() {
        return this.productName;
    }

    public void setProductName(Object productName) {
        this.productName = productName;
    }

    public Object getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Object unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Object getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Object quantity) {
        this.quantity = quantity;
    }

    public Object getDiscount() {
        return this.discount;
    }

    public void setDiscount(Object discount) {
        this.discount = discount;
    }

    public Object getExtendedPrice() {
        return this.extendedPrice;
    }

    public void setExtendedPrice(Object extendedPrice) {
        this.extendedPrice = extendedPrice;
    }
}