package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Order  {

    private java.lang.Integer orderID;  // t
    private java.lang.String customerID;  // t
    private java.lang.Integer employeeID;  // t
    private java.lang.String orderDate;  // t
    private java.lang.String requiredDate;  // t
    private java.lang.String shippedDate;  // t
    private java.lang.String freight;  // t
    private java.lang.String shipName;  // t
    private java.lang.String shipAddress;  // t
    private java.lang.String shipCity;  // t
    private java.lang.String shipRegion;  // t
    private java.lang.String shipPostalCode;  // t
    private java.lang.String shipCountry;  // t

    public java.lang.Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(java.lang.Integer orderID) {
        this.orderID = orderID;
    }

    public java.lang.String getCustomerID() {
        return this.customerID;
    }

    public void setCustomerID(java.lang.String customerID) {
        this.customerID = customerID;
    }

    public java.lang.Integer getEmployeeID() {
        return this.employeeID;
    }

    public void setEmployeeID(java.lang.Integer employeeID) {
        this.employeeID = employeeID;
    }

    public java.lang.String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(java.lang.String orderDate) {
        this.orderDate = orderDate;
    }

    public java.lang.String getRequiredDate() {
        return this.requiredDate;
    }

    public void setRequiredDate(java.lang.String requiredDate) {
        this.requiredDate = requiredDate;
    }

    public java.lang.String getShippedDate() {
        return this.shippedDate;
    }

    public void setShippedDate(java.lang.String shippedDate) {
        this.shippedDate = shippedDate;
    }

    public java.lang.String getFreight() {
        return this.freight;
    }

    public void setFreight(java.lang.String freight) {
        this.freight = freight;
    }

    public java.lang.String getShipName() {
        return this.shipName;
    }

    public void setShipName(java.lang.String shipName) {
        this.shipName = shipName;
    }

    public java.lang.String getShipAddress() {
        return this.shipAddress;
    }

    public void setShipAddress(java.lang.String shipAddress) {
        this.shipAddress = shipAddress;
    }

    public java.lang.String getShipCity() {
        return this.shipCity;
    }

    public void setShipCity(java.lang.String shipCity) {
        this.shipCity = shipCity;
    }

    public java.lang.String getShipRegion() {
        return this.shipRegion;
    }

    public void setShipRegion(java.lang.String shipRegion) {
        this.shipRegion = shipRegion;
    }

    public java.lang.String getShipPostalCode() {
        return this.shipPostalCode;
    }

    public void setShipPostalCode(java.lang.String shipPostalCode) {
        this.shipPostalCode = shipPostalCode;
    }

    public java.lang.String getShipCountry() {
        return this.shipCountry;
    }

    public void setShipCountry(java.lang.String shipCountry) {
        this.shipCountry = shipCountry;
    }
}