package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class OrderSubtotal  {

    private Integer orderID;  // q
    private Double subtotal;  // q
    private int xxx;  // xml(xxx)

    public Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }

    public Double getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    public int getXxx() {
        return this.xxx;
    }

    public void setXxx(int xxx) {
        this.xxx = xxx;
    }
}