package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Product  {

    private java.lang.Integer productID;  // t
    private java.lang.String productName;  // t
    private java.lang.Integer supplierID;  // t
    private java.lang.Integer categoryID;  // t
    private java.lang.String quantityPerUnit;  // t
    private java.lang.String unitPrice;  // t
    private java.lang.Integer unitsInStock;  // t
    private java.lang.Integer unitsOnOrder;  // t
    private java.lang.Integer reorderLevel;  // t
    private java.lang.String discontinued;  // t
    private java.lang.String discontinuedDate;  // t

    public java.lang.Integer getProductID() {
        return this.productID;
    }

    public void setProductID(java.lang.Integer productID) {
        this.productID = productID;
    }

    public java.lang.String getProductName() {
        return this.productName;
    }

    public void setProductName(java.lang.String productName) {
        this.productName = productName;
    }

    public java.lang.Integer getSupplierID() {
        return this.supplierID;
    }

    public void setSupplierID(java.lang.Integer supplierID) {
        this.supplierID = supplierID;
    }

    public java.lang.Integer getCategoryID() {
        return this.categoryID;
    }

    public void setCategoryID(java.lang.Integer categoryID) {
        this.categoryID = categoryID;
    }

    public java.lang.String getQuantityPerUnit() {
        return this.quantityPerUnit;
    }

    public void setQuantityPerUnit(java.lang.String quantityPerUnit) {
        this.quantityPerUnit = quantityPerUnit;
    }

    public java.lang.String getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(java.lang.String unitPrice) {
        this.unitPrice = unitPrice;
    }

    public java.lang.Integer getUnitsInStock() {
        return this.unitsInStock;
    }

    public void setUnitsInStock(java.lang.Integer unitsInStock) {
        this.unitsInStock = unitsInStock;
    }

    public java.lang.Integer getUnitsOnOrder() {
        return this.unitsOnOrder;
    }

    public void setUnitsOnOrder(java.lang.Integer unitsOnOrder) {
        this.unitsOnOrder = unitsOnOrder;
    }

    public java.lang.Integer getReorderLevel() {
        return this.reorderLevel;
    }

    public void setReorderLevel(java.lang.Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public java.lang.String getDiscontinued() {
        return this.discontinued;
    }

    public void setDiscontinued(java.lang.String discontinued) {
        this.discontinued = discontinued;
    }

    public java.lang.String getDiscontinuedDate() {
        return this.discontinuedDate;
    }

    public void setDiscontinuedDate(java.lang.String discontinuedDate) {
        this.discontinuedDate = discontinuedDate;
    }
}