package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class ProductSales  {

    private String categoryName;  // q
    private String productName;  // q
    private Double productSales;  // q

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Double getProductSales() {
        return this.productSales;
    }

    public void setProductSales(Double productSales) {
        this.productSales = productSales;
    }
}