package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class QuarterlyOrdersByProduct  {

    private Object productName;  // q(ProductName)
    private Object customerID;  // q(CustomerID)
    private Object orderYear;  // q(OrderYear)

    public Object getProductName() {
        return this.productName;
    }

    public void setProductName(Object productName) {
        this.productName = productName;
    }

    public Object getCustomerID() {
        return this.customerID;
    }

    public void setCustomerID(Object customerID) {
        this.customerID = customerID;
    }

    public Object getOrderYear() {
        return this.orderYear;
    }

    public void setOrderYear(Object orderYear) {
        this.orderYear = orderYear;
    }
}