package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Region  {

    private Integer regionID;  // t
    private String regionDescription;  // t

    public Integer getRegionID() {
        return this.regionID;
    }

    public void setRegionID(Integer regionID) {
        this.regionID = regionID;
    }

    public String getRegionDescription() {
        return this.regionDescription;
    }

    public void setRegionDescription(String regionDescription) {
        this.regionDescription = regionDescription;
    }
}