package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Region  {

    private java.lang.Integer regionID;  // t
    private java.lang.String regionDescription;  // t

    public java.lang.Integer getRegionID() {
        return this.regionID;
    }

    public void setRegionID(java.lang.Integer regionID) {
        this.regionID = regionID;
    }

    public java.lang.String getRegionDescription() {
        return this.regionDescription;
    }

    public void setRegionDescription(java.lang.String regionDescription) {
        this.regionDescription = regionDescription;
    }
}