package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Sales  {

    private Object categoryID;  // q
    private Object categoryName;  // q
    private Object productName;  // q
    private Object productSales;  // q

    public Object getCategoryID() {
        return this.categoryID;
    }

    public void setCategoryID(Object categoryID) {
        this.categoryID = categoryID;
    }

    public Object getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(Object categoryName) {
        this.categoryName = categoryName;
    }

    public Object getProductName() {
        return this.productName;
    }

    public void setProductName(Object productName) {
        this.productName = productName;
    }

    public Object getProductSales() {
        return this.productSales;
    }

    public void setProductSales(Object productSales) {
        this.productSales = productSales;
    }
}