package com.sqlite.northwindef.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class SalesByYear  {

    private String shippedDate;  // q
    private Integer orderID;  // q
    private Double productSales;  // q
    private String shippedYear;  // q

    public String getShippedDate() {
        return this.shippedDate;
    }

    public void setShippedDate(String shippedDate) {
        this.shippedDate = shippedDate;
    }

    public Integer getOrderID() {
        return this.orderID;
    }

    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }

    public Double getProductSales() {
        return this.productSales;
    }

    public void setProductSales(Double productSales) {
        this.productSales = productSales;
    }

    public String getShippedYear() {
        return this.shippedYear;
    }

    public void setShippedYear(String shippedYear) {
        this.shippedYear = shippedYear;
    }
}