package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Sales  {

    private Integer categoryID;  // q
    private String categoryName;  // q
    private String productName;  // q
    private Object productSales;  // q

    public Integer getCategoryID() {
        return this.categoryID;
    }

    public void setCategoryID(Integer categoryID) {
        this.categoryID = categoryID;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Object getProductSales() {
        return this.productSales;
    }

    public void setProductSales(Object productSales) {
        this.productSales = productSales;
    }
}