package com.sqlite.northwindef.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Territory  {

    private java.lang.Integer territoryID;  // t
    private java.lang.String territoryDescription;  // t
    private java.lang.Integer regionID;  // t

    public java.lang.Integer getTerritoryID() {
        return this.territoryID;
    }

    public void setTerritoryID(java.lang.Integer territoryID) {
        this.territoryID = territoryID;
    }

    public java.lang.String getTerritoryDescription() {
        return this.territoryDescription;
    }

    public void setTerritoryDescription(java.lang.String territoryDescription) {
        this.territoryDescription = territoryDescription;
    }

    public java.lang.Integer getRegionID() {
        return this.regionID;
    }

    public void setRegionID(java.lang.Integer regionID) {
        this.regionID = regionID;
    }
}